### ISSUE TITLE
Running tests hangs and does not complete

### ISSUE THREAD

**Issue by billbsing** [Convex-Dev/convex#130]
On my desktop this is about 80% of the time.

convex.cli.CLITest also reports the incorrect test run count ( 78 !) should be 3.

Testing still hangs if I disable CLITest

```
[INFO] Running convex.cli.CLITest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in convex.core.data.BlobsTest
[INFO] Running convex.store.EtchInitTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in convex.core.lang.ReaderTest
[INFO] Running convex.gui.GUITest
[INFO] Tests run: 78, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.143 s - in convex.cli.CLITest
[INFO] Running convex.actors.OracleTest
```

Currently to fix I need to turn off parallel testing

`junit.jupiter.execution.parallel.enabled=false
`
at https://github.com/Convex-Dev/convex/blob/master/src/test/resources/junit-platform.properties

**Comment by helins** [comment]
This is irrelevant now, isn't it?

**Comment by billbsing** [comment]
yes we can close
