### ISSUE TITLE
Chars are stringified as symbols

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#152]
This one was causing extremely weird and specific edge cases in my gen tests. It took more than 2 hours to track. It turns out that `CVMChar` is stringified as a symbol. You can even try it in the sandbox with an expression that needs to use `.toString` on the result:

```clojure
(fn [] \a)

;; => (fn [] a)
```

Would fixing this break anything?

**Comment by mikera** [comment]
Want to fix this for Alpha release @helins ?
