### ISSUE TITLE
Improve error: Unrecognized `##` values

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#156]
Reported position is correct but error message for an illegal `##` value is empty. Examples:

```clojure
##InF

;; READER: Reader error: Parse error at Position{line=1, column=5} Source: <F> Message: null

##Nan
##foo
```

**Comment by mikera** [comment]
Might be fixed by replacement reader.

**Comment by helins** [comment]
Fixed, ANTLR reports an invalid special literal.
