### ISSUE TITLE
Should recursion enforce tail position?

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#177]
I am curious if there is a reason for fhis behavior or if it is an oversight:

```clojure
(loop [a 10] 
  (if (zero? a)
    :good 
    (recur (dec a)))
  :bad)
```

The recursion happens (you can tell by using `log`). However it is useless (discarded) and `:bad` is returned.

Clojure enforces that `recur` can be used only from "tail" position. In other words, it can only figure in the last position of any branch encompassed by the recursion point. Otherwise you end up with cases like this one where the shape of the loop looks wrong.

From what I remember, it is because `recur` is implemented as an exceptional state. I guess it should be the job of the compiler to ensure that its usage is sensible and not error-prone?

**Comment by mikera** [comment]
We will keep this behaviour in core for now, it's consistent with `recur` and `return` etc. and gives people a bit more flexibility. Option to analyse with linter etc. in external tools.
