### ISSUE TITLE
`doc` does not work with qualified symbol

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#206]
![Screenshot from 2021-06-24 11-32-37](https://user-images.githubusercontent.com/17478152/123239794-01080e00-d4e0-11eb-8b09-d6a6121f2883.png)

Because it expands to:

```clojure
(:doc (lookup-meta (quote (lookup a foo))))
```

**Comment by helins** [comment]
Actually it's probably best to remove it.

It's the job of the consumer (sandbox, CVX runner) to display documentation. You literally never have to use `doc` directly. Anyways, a function would me more useful than a macro and you can always use `lookup-meta` actually, it doesn't deserve a dedicated core symbol.

**Comment by mikera** [comment]
I'd like to keep `doc` as a REPL based way of showing docs, which does not require a fancy client.
