### ISSUE TITLE
Occasional fuzz test failure with Sets

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/convex#217]
Sometimes, a failure occurs in the generative fuzz tests: it is possible to construct a set with invalid structure (i.e. a non-CVMBool value in place of an expected Boolean)

Fixes:
- Better validation of Set structure
- Create dedicated set implementation rather than backing with a map

**Comment by helins** [comment]
Interesting, it is true that I did not test fuzzing with non-CVM values since I was focused on what is accessible from Convex Lisp.

**Comment by mikera** [comment]
Technically these are not accessible from Convex Lisp but could be still be Peer bugs (since someone might be able to construct an adversarial message). The fizz testing catches them eventually, but it's not totally consistent and needs a more systematic review I think.

**Comment by mikera** [comment]
Fixed by creating a dedicated Set implementation with better validation
