### ISSUE TITLE
Should `*lang*` be recusive?

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#251]
I had the same problem when I was implementing a "transaction hook" in the CVX runner which was pretty much doing the same job as `*lang*`.

The problem is that code like that results in an infinite look (hence a DEPTH exception):

```clojure
(def *lang* (fn [x] (eval x))

42
```

**Solution**: undef `*lang*` and then redef it if needed.

**Question**: should the solution be at the level of the CVM or at the level of the user in CVX? Not having named functions make it slightly painful reattaching the same function.

**Comment by mikera** [comment]
`*lang*` sort of needs to be at user level if we want it to be fully usable by user code. The question is more about the semantics of `eval`, it is currently "execute this code as if evaluated in this account as a top level form". Which of course results in infinite recursion if `*lang*` is set.

Possible options:
- Limit `eval` to ignore `*lang*` (but this makes it harder to interact with custom languages?)
- Explicitly compile the form, which will circumvent `*lang*` e.g. `(def *lang* (fn [x] (eval (compile x))))`
- Have a separate `eval-core` function which does `(eval (compile ...))` to get the core language semantics

**Comment by helins** [comment]
It's true that `(eval (compile x))` circumvents the problem. Maybe all that's needed is good doc for `*lang*` and assume that it targets expert-iish users?

**Comment by mikera** [comment]
Yes I think I favour this approach. Regular users almost certainly shouldn't be setting `*lang*` unless they know what they are doing. And the Account is still recoverable even if they mess up.

**Comment by helins** [comment]
Can it rather be a global nil value? So that it shows up clearly in documentation.

**Comment by mikera** [comment]
Probably let me check

**Comment by helins** [comment]
Given `*lang*` is now interned and can be documented, let's leave things as they are.
