### ISSUE TITLE
Question regarding `*result*` behaviour

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#252]
While `(do 42 *result*)` does return `42`, anything more than that seems to fail oddly:

```clojure
(do 42 (inc *result*))  ;; Cast error: Can't convert argument at position 1 (with type Function) to type Long

(do 42 (str [*result*]))  ;; "[vector]" ???
```

**Comment by mikera** [comment]
Result is always defined to be the result of the last op executed, e.g. what you are seing is the reult of the ops that fetch `inc` and `vector` (for the vector constructor).

If you can see a better way of defining this happy to consider. Perhaps `*result*` shouldn't be available to user code though, I haven't seen many good use cases.

**Comment by helins** [comment]
Right, it makes sense if you get that it's about ops. I thought intuitively it was about the previous "form". If I got confused by that, then chance is that many people will. In any case, given that, I can't envision a use case so removing it is definitely an option.
