### ISSUE TITLE
Replacing `export` with metadata

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#259]
(I don't think it is solved yet, sorry it is)

Idea is to replace current `export` mechanism with a simple `:callable?` metadata on the interned function. Looks like a straightforward update on `.getExportedFunction` (`AccountStatus`).

However this is going to break quite a lot of tests, at least tests for CVX libraries. I know those tests are adding extra security checks regarding Convex Lisp. However they are quite limited in comparison to what the CVX runner allows you to do, while being hard to write. So I suggest simply removing them once I'm done with porting them to CVX and toughen the `Core` unit tests. Libraries should be tested very thoroughly, the process should be easy, provide good feedback and allow to test more complex scenarios, which is all a pain to do in Java.

What's your take?

**Comment by mikera** [comment]
Just make `export` macro set the metadata flag. This shouldn't break any tests (unless there is a conflict with something that constructs metadata)

**Comment by mikera** [comment]
Happy to do this, I think good to get in for alpha. But if you fancy  go at ot, let me know and drop me a PR!
