### ISSUE TITLE
Fatal error: Double unquoting of an inexistant symbol

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#262]
I think I boiled down the problem to this, unquoting an inexistant symbol twice results in a fatal error:

![Screenshot from 2021-08-02 10-52-41](https://user-images.githubusercontent.com/17478152/127833264-d25e907a-4702-4e9a-9efc-f17aa8c1cf74.png)

**Comment by mikera** [comment]
Fixed in develop, thanks. Another CVM bug bounty!
