### ISSUE TITLE
Comparing keys is counter-intuitive

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#266]
Implementation-wise, a key is a specialized blob. However, in CVX Lisp, that distinction is hidden from the user as there is no point in having one.

The following example is still a bit surprising and at least error-prone:

```clojure
(do (def k 0x0000000000000000000000000000000000000000000000000000000000000000)
    (def a (deploy `(set-key ~k)))
    (= k (:key (account a))))

;; <!> False, you'd have to explicitly convert the `a` key to a blob.
```

**Comment by mikera** [comment]
I think that's a bug, the two should be equal. Will check.
