### ISSUE TITLE
Quasiquote erases metadata (+ regression on callable functions)

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#267]
```clojure
;; Regular quoting
'(defn foo ^{:a :b} [])

;; -> (defn foo ^{:a :b} [])  ;; Metadata preserved

;; Quasiquoting
`(defn foo ^{:a :b} [])

;; -> (defn foo [])  ;; Metadata disappears!
```

Which is really bad for templating actors, like the Trust library which creates lists, since you cannot attach `:callable?`. All my tests are failing because of that.

**Comment by mikera** [comment]
I think this may be fixed in recent commit, but some extra testing appreciated!

**Comment by helins** [comment]
Seems to behave well at the REPL and tests for the Fungible and Trust libs now pass (both are templating `:callable?` functions). Looks good! I'll adapt more libs this evening if you want more feedback but it might be too late for Singapore.

**Comment by mikera** [comment]
Good to hear! I can pick up tomorrow, no problem :-)
