### ISSUE TITLE
Do not erase library account in function calls

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#277]
Suppose:

```clojure
(def a1 (deploy nil))

(def a2 (deploy `(do (def a1 ~a1) (defn foo [] (a1/bar)))))
```

First problem is that printing the function is misleading, `bar` is presented as local to `a2` instead of `a1`:

```clojure
a2/foo

;; (fn [] (bar))
```

Second problem is that this results in misleading `:UNDECLARED` exceptions:

```clojure
(a/foo)

; Exception code:
;  :UNDECLARED
; Message:
;   bar
; Trace:
;   In function: (fn [] (bar))
```

Any non-trivial example is really hard to debug unless you know exactly what the code does and remember all the above.

**Comment by mikera** [comment]
I would expect an UNDECLARED error if you try an access a symbol that is not in the target actor.

Is the problem simply with how the lookup gets printed?

**Comment by helins** [comment]
Yes, but after hacking for the past hour, it's harder to solve than it looks.

The core problem resides in `Lookup` it seems. In principle, following comments and `.execute`, `Lookup` does not have an `.address` (Op resolving to an address) if lookup is meant to be local, so it would have been easy detecting a local lookup and not printing `.address` similarly to:

```java
	@Override
	public void print(StringBuilder sb) {
		if (address == null) {
			symbol.print(sb);
		} else {
			address.print(sb);
			sb.append('/');
			symbol.print(sb);
		}
	}
```

However, this is not the case. When symbols are compiled to lookups, the address is always provided as a constant op. `Lookup.execute` should be update because I don't think there is a case anymore where `.address` is null.

Problem is: `Lookup` cannot know whether a lookup is local or not. So the only solution is to always print a full lookup form. This will make code harder to read (every symbols access will be a lookup form), but at least it will be 100% accurate.

What do you think?

**Comment by helins** [comment]
Not storing the address as a constant op results when compiling symbols results in catastrophic errors when calling libraries.

**Comment by mikera** [comment]
It would be nice if we could avoid expanding prints of lookups differently from how they are written.  I guess it is somewhat unavoidable if you want to maintain the context in which  library function is compiled. That suggests a trade-off - do we want printing to mainly support human readability or information preservation?

Maybe a compromise is printing something like `#123/foo`, which is  bit less noisy, keeps the account address and should still compile to a lookup?

**Comment by helins** [comment]
My original fix systematically printing `(lookup x y)` was a bit ugly, granted, but it was consistent. The problem with using `/` is that it can print faulty forms:

```clojure
(str (fn [] (lookup (foo) bar)))
;;  "(fn [] (#60/foo)/bar)"
```

Need to check if `address` is a `Constant` or a `Lookup` to print with `/`, right? Revert to `(lookup ...)` otherwise. Then I guess this example would print: `(lookup (#60/foo) bar)`.

What do you think? I'm not sure I like mixing 2 representations of the exact same principle.

**Comment by mikera** [comment]
This needs further thought. 

In principle, allowing `(#60/foo)/bar` or `#60/foo/bar` might be reasonable, assuming we can get the semantics right for reader, compiler and printer. Basically `/` becomes syntactic sugar for a lookup in all cases.
