### ISSUE TITLE
Should the registry allow registering inexistent accounts?

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#278]
Current, the `cns-update` function in the registry allows registering any address, even if it does not exist. This does not really make sense so I would tend to add an extra check forbidding that. On the other hand, it looks rather harmless. Is there any vector attack that could sprout from this?

**Comment by mikera** [comment]
It's probably worth checking? There is a risk that if someone depends on a non-existent account in a way that affects security, and attacker could create accounts until they get the account number they need to launch an attack

**Comment by mikera** [comment]
Replaced with new implementation
