### ISSUE TITLE
Has `hash?` become irrelevant?

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#283]
From Convex Lisp, there should be only one acknowledged blob type (besides addresses). Hence `hash?` feels outdated, furthermore it leads to counter-intuitive results:

```clojure
(hash? (blob (hash (encoding 42))))

;; False
```

**Comment by mikera** [comment]
Agreed. Will remove `hash?`.

**Comment by helins** [comment]
Fixed.
