### ISSUE TITLE
Should `actor` and `defactor` be removed?

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#285]
I believe `actor` and `defactor` are obsolete since `quasiquote`. They are a bit too magical. Using `quasiquote` is actually clearer IMO, albeit being a bit more expert-friendly. It is always obvious that data is manipulated, as opposed to `actor` which kind of hides that. As proof, we could have used `defactor` a few times in our libs but never did.

**Comment by mikera** [comment]
Possibly. I do think there is scope for a good user-level syntax for creating parameterised actors, but maybe somethings like the following is enough in most cases:

```clojure
(deploy (build-actor-function foo bar))
```

**Comment by helins** [comment]
Okay, then I'd like to remove them knowing we can always add something better later. I think it's one of those cases where trying to make things simpler actually makes them more opaque and complicated for users.

**Comment by mikera** [comment]
Done in latest `develop`
