### ISSUE TITLE
NPE when printing `Ref` without hash

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#295]
`.print` involves getting the hexstring of `Ref`'s hash, which fails when hash is null.

**Comment by mikera** [comment]
`print` probably shouldn't possible for a Ref (should only apply to CVM values whereas Ref is an internal construct), but worth fixing anyway

**Comment by helins** [comment]
Annoying when working at the REPL ;)

**Comment by mikera** [comment]
Done a quick fix for this!
