### ISSUE TITLE
`Store.current` might return null

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#296]
Intuitively, one might set current store to null so that it would default to the default store. This is what happens when setting the global store.

However, unlike getting the global store which checks for null and returns the default store if needed, getting the current store returns systematically the thread local value. So, if someone set the current store to null, NPE will happen further down the road when using `ACell.createPersisted` for instance.

Would checking for null in `.current` induce a perf hit?

**Comment by mikera** [comment]
Probably if someone sets the current store to null, they would want any subsequent use of the store to fail anyway?

A scenario I can thing of where this makes sense is during shutdown setting a store to null.

**Comment by helins** [comment]
I'm mostly concerned about the behavior being different between `Stores.setCurrent()` and `Stores.setGlobalStore()` when it comes to handling null. But not at the point to prevent me from sleeping at night. As long as it is documented and you think it's not tricky, we can close the issue.

**Comment by mikera** [comment]
Added some docs. I think relatively safe, setting to null will cause errors but I think that is expected behaviour.
