### ISSUE TITLE
Etch: Reads `Blob` instead of `Hash`

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#297]
Persisting a `Hash` and reading it back returns it as a `Blob` instead of `Hash`. `Address` is returned as `Address`, as expected, in spite of being a specialized blob as well.

**Comment by mikera** [comment]
This is expected. A `Hash` is not a distinct type from the perspective of the CVM, it is a Java implementation detail.

Java code should use `RT.ensureHash(...)` if you explicitly need a Hash instance.

**Comment by helins** [comment]
I don't know if the following is related but it rings a bell. When messing with Etch and the binary client, working with `convex.world`, I got in a situation where the following line was throwing an exception on transaction (only, not queries):

https://github.com/Convex-Dev/convex/blob/2d214e0f79cdacd57b5fd19525e629e578fc397e/convex-peer/src/main/java/convex/net/ResultConsumer.java#L72

```
21-08-30 13:58:58 dvlopt WARN [convex.net.ResultConsumer:51] - Failed to accept message! {}
                              java.lang.Thread.run           Thread.java: 831
                       convex.net.Connection$1.run       Connection.java: 651
                  convex.net.Connection.selectRead       Connection.java: 688
        convex.net.Connection.handleChannelRecieve       Connection.java: 716
     convex.net.MessageReceiver.receiveFromChannel  MessageReceiver.java: 135
         convex.net.MessageReceiver.receiveMessage  MessageReceiver.java: 164
                        convex.api.Convex$1.accept           Convex.java:  97
                        convex.api.Convex$1.accept           Convex.java: 122
                  convex.net.ResultConsumer.accept   ResultConsumer.java:  39
convex.net.ResultConsumer.handleMissingDataRequest   ResultConsumer.java:  72
java.lang.ClassCastException: class convex.core.data.Blob cannot be cast to class convex.core.data.Hash (convex.core.data.Blob and convex.core.data.Hash are in unnamed module of loader 'app')
```

**Comment by mikera** [comment]
Yes that's plausibly an issue, might result in missing data requests getting ignored in some cases. Good spot!
