### ISSUE TITLE
`Ref.createPersisted` do not persist some types

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#298]
`Ref.createPersisted()`  writes only if `ref.isPersisted()` returns true.

Problem is that `.isPersisted()` check is ref status is >= 2 (`Ref.PERSISTED`). Some types, such as CVM primitives or `Address`, create refs with status higher than that although those fresh refs have not been persisted yet. As a result, they are can never be persisted by `.createPersisted()`.

Shouldn't `.isPersisted()` be implemented with a bit AND against `Ref.PERSISTED` instead of `>=`? Like usually done with bit flags?

**Comment by mikera** [comment]
Some CVM types don't need to be persisted (since they are classified as Embedded and have no child refs). This includes `Address` and various small primitives. Under normal circumstances, we want to avoid persisting small embedded values to the store.

**Comment by helins** [comment]
The way I'm was using Etch differs from the main purpose of storing CVM states. That's why I was having that kind of surprising effects, like exposed in #299.

**Comment by mikera** [comment]
It's technically possible to to force a write to the store for any Cell (even embedded ones). @helins if you need to do that let me know.
