### ISSUE TITLE
Cannot use all funds as stake with `create-peer`

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#307]
```clojure
(create-peer 0x42ae93b185bd2ba64fd9b0304fec81a4d4809221a5b68de4da041b48c85bcc2e
             *balance*)
             
;; FUNDS: Insufficient balance (98000000) to assign an initial stake of 98000000
```

Indeed:

https://github.com/Convex-Dev/convex/blob/2e3e32b83d51001dd72bd32625bd554c682a677d/convex-core/src/main/java/convex/core/lang/Context.java#L2022

Is there a reason why it is `>=` and not `>`?

**Comment by mikera** [comment]
I think allowing the full balance to be set as stake is reasonable. Will do a quick fix
