### ISSUE TITLE
Resolve missing data by default

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#310]
*(Just so to keep a trace and potentially discuss it further)*

As discussed earlier, sane default would be to resolve any missing data in results on behalf of the consumer. It is especially relevant for a common client which simply wants to transact/query stuff eargerly. Putting results on a queue is probably the right way to tackle this because it is best to keep a fully async API from the point of view of the consumer.

Naturally this doesn't forbid the idea of allowing lazy operators which only want to resolve missing data as late as possible. Just that those are probably more complex use cases, albeit interesting ones, that would make sense to investigate more thoroughly at a later stage.

**Comment by mikera** [comment]
I've done some refactoring with the default ResultConsumer to ensure that missing data gets handled *before* the result is delivered to any callback. This is probably a decent interim solution. Consumers can always use the callback to place results on a queue if desired.

**Comment by helins** [comment]
Seems to behave well. At the REPL at least. Shall we close or do you envision we should think about a better approach?

**Comment by mikera** [comment]
I think this specific issue is done. We might refactor later, but will probably keep this behaviour.
