### ISSUE TITLE
`empty?` should operate on `ACountable`

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#342]
I noticed `empty?` is not quite right.

1) I would prefer Clojure's behavior of failing when arg is definitely not a coll (eg. `(empty? 42`)
2) Should work on `ACountable`, not only `ADataStructure`, otherwise `(= false (empty? ""))`

**Comment by mikera** [comment]
Agree, `empty?` is more of a countable thing. `nth`, `count` and `empty?` should probably always be consistent.
