### ISSUE TITLE
`min` and `max` mishandle `-0.0`

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#366]
It's been a long while since I found a small inconsistency. Very good sign!

Anyhow, both return positive `0.0` which is arguably incorrect:

```clojure
(min -0.0)
(max -0.0)
```

**Comment by jeroenvandijk** [comment]
I think this issue is related to the implementation [here](https://github.com/Convex-Dev/convex.cljc/blob/4a36f56a40bcdd7762ee088344844547c378fefc/src/convex/lang/core.cvx#L195). 

As far as I can tell this should be `(assert (number? 0))` instead `(+ fst 0)`. Same goes for the implementation of `max`.

With this implementation `(min 1 nil)` also gives a very cryptic and verbose error message. An assert here would be much clearer.

<img width="386" alt="Convex" src="https://user-images.githubusercontent.com/27645/172926560-d4ae888c-e870-4fd3-989f-581033a51bf1.png">

**Comment by mikera** [comment]
I'm tempted to rewrite in Java for performance reasons (range checks are very important for tokens etc.)

**Comment by helins** [comment]
Yep, @jeroenvandijk is right. There are a couple ways this could be reimplemented. However, those are indeed important primitives for a lang centered on the notion of assets, so a quick Java implementation is sensible

**Comment by mikera** [comment]
Semantics are quite interesting. I think the simplest is simply to take the the first value where multiple values are numerically equal, but this does lead to some interesting edge cases:

```
(min 0.0 -0.0) => 0.0
(min -0.0 0.0) => -0.0
```

Since `0.0` and `-0.0` are numerically equal.

**Comment by helins** [comment]
Ah... That is a bit unsettling. You're right about numerical equality between zeroes. Yet Clojure returns consistently `0.0` on `max` and `-0.0` on `min`. Actually, they are implemented in terms of `Math/max` and `Math/min`, so it's a JVM thing.

**Comment by mikera** [comment]
We could also just copy the JVM behaviour of course. Might be most understandable.

IEEE754 doubles are tricky... there is no "perfect" solution often.

**Comment by helins** [comment]
https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/lang/Double.java#l959

(got that after asking on Clojurians Slack ; yeah, let's use `StrictMath/min` and `StrictMath/max`, at least it's accepted behavior that has been thoroughly reviewed)

**Comment by jeroenvandijk** [comment]
Maybe also related (or otherwise a seperate issue), in Clojure the following is true, but not in Convex

`(= 0.0 -0.0)`

**Comment by helins** [comment]
`(== 0.0 -0.0)` is still true, which is the most important since `==` is what should be used for numerical equivalence (ensures type erasure).
But since `0.0` and `-0.0` are both doubles, I'd argue that `(= 0.0 -0.0)` should be true as well. I know it doesn't look like such a big deal but talking about zeroes on Clojurians Slack made me realize subtle bugs could arise in practice: https://clojurians.slack.com/archives/C03RZGPG3/p1655152326487629

**Comment by mikera** [comment]
`(= 0.0 -0.0)` cannot be true because it violates the important contract of `=` (true if and only if values are identical in representation)

`(== 0.0 -0.0)` is fine being true because it is consistent with mathematical meaning of numbers and IEEE754
