### ISSUE TITLE
Missing double? function

### ISSUE THREAD

**Issue by Darkneew** [Convex-Dev/convex#373]
There is no double? function

double? would be equivalent to (fn [x] (and (number? x) (not (long? x)))), but this doesn't feel right and won't work if a new type of number is added someday

As such, I think this function should be implemented

**Comment by Darkneew** [comment]
Apparently @mikera implemented this function for the next release, I'm thus closing the issue

**Comment by mikera** [comment]
Thanks @Darkneew ! Yes `double?` is now implemented.
