### ISSUE TITLE
Error in argument compilation

### ISSUE THREAD

**Issue by Darkneew** [Convex-Dev/convex#377]
There is an error which I guess comes from argument compilation. However, I don't know how the reader and parser work, so I can only show how to reproduce the error. 

First, I define an actor with an eval callable function:
```clojure
(def actor (deploy `(
    defn eval ^{:callable? true} [code] (
        if (= *caller* ~*address*) 
            (eval-as *address* code) 
            (fail :UNAUTHORIZED "access not granted")
    )
)))
```
Then, I create a function that use a variable in actor, using the eval function
```clojure
(call actor (eval `(
    defn identity [arg] arg
)))
```
Finally, I run the function with some value
```clojure
(actor/identity 1)
```
And instead of returning 1, it returns 
```
(defn identity [arg] arg)
```

**Comment by mikera** [comment]
Interesting one. Let me check and get back on this!

**Comment by mikera** [comment]
OK the problem is that `(eval ``(....)` with the syntax quotes behaves differently from `(eval '(...))` with a normal quote. Will need to check why.
