### ISSUE TITLE
`assoc-in` accepts syntax as path

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#383]
```clojure
(assoc-in {:foo :old} ^{} [:foo] :new)
;; {:foo :new}
```

Seems a bit unorthodox.

**Comment by mikera** [comment]
I think that's fine? 

From the perspective of the compiler, it's just a vector with some empty metadata.

**Comment by helins** [comment]
Indeed, my mistake, I was somehow under the impression that syntax would return a `Syntax` (it does not).
