### ISSUE TITLE
Fatal: `conj` non-blob key on blob-map

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#386]
Found in gen tests:
```clojure
(conj (blob-map #0 #0) [false #0])
```
<img width="1159" alt="Screenshot 2022-08-15 at 18 12 37" src="https://user-images.githubusercontent.com/17478152/184672989-95ccda11-625d-4717-9b4a-07620f73ad69.png">

**Comment by mikera** [comment]
Fixed now I think, thanks for the catch @helins !
