### ISSUE TITLE
`AString.print` does not escape double-quotes in outputs

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#393]
This can also be seen in the sandbox:

```clojure
(str "ok \"test\" foo")

;; returns

"ok "test" foo"
```

Which does not look right and makes the output unusable for the CVX reader.

**Comment by mikera** [comment]
Yup, we need to distinguish between `toString` type behaviour and `print` behaviour when using Strings. This is mostly all in place, just needs a bit more checking on the edge cases. Have implemented Java-style escaping in `AString.print` which should fix this specific problem.

**Comment by mikera** [comment]
Basically, if you plan to read a string, you should use `print` not `str`

**Comment by helins** [comment]
Seems to behave well so far.
I'll give it a final go after support for octal escaping is added back to the reader

**Comment by mikera** [comment]
This specific issue fixed I think. Let me know if any related problems (new issue if needed)

**Comment by helins** [comment]
Seems fine and octal escaping works, thanks 👍
