### ISSUE TITLE
Cannot open Etch instance on Java 11

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#394]
The Java test suit does pass using a Java 11 JVM but I noticed in my Clojure tests that opening an Etch instance throws an exception:

```
Exception: java.lang.NoSuchMethodError: 'java.nio.MappedByteBuffer java.nio.MappedByteBuffer.duplicate()'
 at etch.Etch.seekMap (Etch.java:245)
    etch.Etch.<init> (Etch.java:157)
    etch.Etch.createTempEtch (Etch.java:214)
    etch.EtchStore.createTemp (EtchStore.java:91)
```

Java 17 has a `.duplicate` method on `MappedByteBuffer` while Java 11 locates it in `ByteBuffer`.

**Comment by mikera** [comment]
That's a bit strange, since `MappedByteBuffer` implements `ByteBuffer` and therefore inherits `duplicate`. Should be equivalent? Any idea what is going on?

**Comment by mikera** [comment]
Hmm  might be a different between the interface and concrete class return type getting confused. Will try a patch.

**Comment by helins** [comment]
Seems fixed with the new casting to `ByteBuffer`.

Not sure what happened but I suspect it was somehow linked to this slight difference between 11 and 17 + using a jar compiled against 17 (that might be why tests were passing, compilation and testing is done with the same JVM).

**Comment by helins** [comment]
Ah well... I must have mixed my JVMs because oddly it is not solved as I thought.

Repro: compile jar from Java 17 but consume jar from Java 11.

It affects the 0.7.8 release but not urgent as fact as I'm concerned.

**Comment by helins** [comment]
I'm setting up CI for the Clojure repo and it fails like that as well.

**Comment by helins** [comment]
Actually, it also fails on Java 15.

**Comment by mikera** [comment]
Fixed now
