### ISSUE TITLE
Fatal: Compiler throws NPE with ill-formed `defn` argument bindings

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#395]
Seems to happen specifically when the first bindings are not proper symbols:

<img width="1137" alt="Screenshot 2022-09-05 at 14 23 25" src="https://user-images.githubusercontent.com/17478152/188448337-e95f79ff-76d0-406f-8801-36843276758b.png">

Bad later symbols are handled as a proper CVM exception:

<img width="394" alt="Screenshot 2022-09-05 at 14 24 11" src="https://user-images.githubusercontent.com/17478152/188448472-5dc3af4c-567e-4022-8cc8-f361586f8b8b.png">

**Comment by helins** [comment]
Same applies to `defmacro`.

**Comment by mikera** [comment]
On the case, thanks! Good spot!
