### ISSUE TITLE
Log errors using SLF4J

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#396]
There are a few places in the codebase where stacktraces of caught exceptions are printed after logging an error message.  
E.g. https://github.com/Convex-Dev/convex/blob/master/convex-core/src/main/java/etch/Etch.java#L567-L568

However, SLF4J does take `Throwable`s as second argument so it would be more convenient for users passing the exception altogether and letting appenders do whatever they want rather than printing the trace.

**Comment by mikera** [comment]
Yup agree. The printing is mostly just there for debugging purposes at the moment. We should remove and replace with logging and/or alternative handling.

**Comment by helins** [comment]
There are still quite a few of those `e.printStackTrace` in `convex-core` and `convex-peer`

**Comment by mikera** [comment]
Have removed remining `printStackTrace` usages.

In cases where we would have printed such a message in `convex-core` library code, exceptions are generally thrown - it is up to application code to catch and decide what to do (e.g. logging, or some sort of error recovery)
