### ISSUE TITLE
Closing an Etch instance should release lock

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#398]
Currently, closing an Etch instance do not release the acquired file lock. Is there any reason why it shouldn't be released?

**Comment by mikera** [comment]
I think closing the file releases the lock autoatically, see:

https://stackoverflow.com/questions/421833/when-using-javas-filelock-is-it-ok-to-let-close-to-automatically-do-a-lock-r

So this appears to be  non-issue, unless there is a concrete problem ocurring?

**Comment by helins** [comment]
Oh well, I reached a situation where I was sure it wasn't being released and thought I could reproduce it. But I can't reproduce it today. I did reboot, maybe some background process was preventing it the other day. My bad.
