### ISSUE TITLE
Pluggable Ed25519 implementations

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/convex#404]
We should make our implementations for Ed25519 fully pluggable. Reasons:

- Support different Ed25519 libraries for different deployment constraints (native libraries vs. pure Java etc)
- Support different JVM versions which have differing Ed25519 support
- Support different validation / signature strategies e.g. batch validation

Benchmarks by @helins suggest that direct libsodium or BouncyCastle may be the best implementations

**Comment by helins** [comment]
Note: I'll first reproduce benchmarks on a CI matrix across platforms and JVM.

**Comment by mikera** [comment]
Done with latest pluggable implementation support
