### ISSUE TITLE
Single quotes in strings are wrongfully escaped in `.print`

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#407]
While updating `convex-web`, I noticed single quotes were being escaped in strings:

```clojure
 "Can't convert value of type Long to type Sequence"
```

On `.print` becomes:

```clojure
"\"Can\\\'t convert value of type Long to type Sequence\""
```

And when read back:

```clojure
"Can\'t convert value of type Long to type Sequence"
```

**Comment by mikera** [comment]
Confirmed we were emitting an unnecessary backslash for single quotes when escaping swings. Easy fix :-)
