### ISSUE TITLE
`Address` should only cast to `Blob` and `Long` 

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#431]
```clojure
(= (byte #5455)
    79)

(= (double #42)
    42.0)
```

The above doesn't make quite sense from a user perspective. At the very least, it doesn't serve any purpose. Casting to a `Long` does since that's how users would think about addresses (being a `Blob` if more of an implementation detail).

**Comment by mikera** [comment]
Sounds sensible, only thing we really need to check is if this is consistently explainable with respect to other numerical rules

**Comment by mikera** [comment]
Fixed in recent versions
