### ISSUE TITLE
`Byte` coercions

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#432]
(In line with other issues discussing implicit Vs explicit coercions)

Currently, `Byte` works with `double` , `char`, `boolean`, etc. That's a somewhat implicit conversions, but it is okay IMO since a `Byte` is arguably an `Integer`.

Either we assume this to be true and then make it work with `blob` like `Long` does. Either we assume the opposite and force users to cast to `Long` explicitly before using any of the above.

**Comment by mikera** [comment]
`Byte` is technically a number so implicit casts to wider numbers should be supported.

Semantics of `blob` would be tricky. Does `0xff` turn into the Blob `0xff`, `0x00000000000000ff` or even `0xffffffffffffffff`?

I'm tempted to narrow `blob` rather than assuming any of these?

**Comment by mikera** [comment]
Bytes no longer exist as an independent integer type on the CVM. We should probably close this (though still need to consider Integer <-> Blob conversion behaviour: do we choose the minimal blob representation?)
