### ISSUE TITLE
`map` should be type consistent with `filter`

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#433]
Currently, `map` behaves like `mapv`: it always returns a vector.

Besides having redundant functions, this does not look good WRT `filter` which does preserve the type of the input collection. Looks like it is time to update `map` so that it preserves the input type as well.

**Comment by mikera** [comment]
This is an interesting question: Should `map` preserve structure on Maps, Sets and BlobMaps as well?

If we say that `map` always converts into a sequential data structure, vectors make sense as the result type.

If we say that `map` preserves types, it should arguably preserve Maps and Sets also.... but then the possibility of overwriting keys becomes an issue etc.

**Comment by helins** [comment]
As often, whatever the decision, consistency is key. Which leaves only 2 options:

a) Make `filter` return a vector as well and remove `mapv`. 

b) Make `map` preserve the input type. I can see how overwriting map keys is not ideal but what are other problems?

`map` and `filter` will probably be used quite differently than Clojure's counterparts. Without the sequence abstraction and conscious of cost / performance, it feels like preserving the input type might be more useful on average but it is hard to tell.

**Comment by oakes** [comment]
Maybe it's worth thinking about which approach would make more sense once transducers are implemented (issue #172). If `map` always returns a vector, you could implement the two arg arity later as simply `(transduce (map inc) conj coll)`.

**Comment by helins** [comment]
Good angle!

I toyed enough with transducer-like ideas to be confident that they are doable in Convex Lisp. There were some constraints in comparison to Clojure, notably when it came to stateful transducers, but I went pretty far. However, the problem is they are probably quite expensive to run. Many higher-level constructs like that only become efficient when supported by the compiler out of the box or through JIT optimization. I have since then put transducers aside, envisioning there may be a better abstraction yet to be find. Note also that we try to keep the compiler as simple as possible so that it can run on-chain with a reasonable cost (as opposed to performing complex optimizations that may not even pay off for one-time transactions).

I think the reason why this question here is not obvious to solve is because `O(n)` algorithms deserve special consideration. They make estimating the transaction cost a lot more uncertain (unless you know `n`) and don't scale very well. Even without worrying too much about it, in all the Convex Lisp I've written, I simply haven't used `map` or even `loop` that often 🤔

**Comment by mikera** [comment]
Looked at this more @helins and @oakes , it's somewhat complicated by the fact that `map` can take multiple collections, like `(map foo {:a 1 :b 2} [1 2] '(3 4))` where `foo` is an arity 3 function. 

I guess the expected behaviour is to preserve the type of the first collection?

On transducers, I think it is unlikely we will implement them as a core feature on the CVM, for the reasons @helins mentions.

In general though, I think preserving type is the logical way to go, so try to implement this and see how it works.

**Comment by mikera** [comment]
Improved `map` looks good to go!
