### ISSUE TITLE
Shouldn't be possible to transfer NFTs to the NFT actor itself

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/convex#44]
Currently NFT actor seems to accept transfers of NFTs to itself:

```clojure
(import convex.nft-tokens :as nft)

(call nft (create-token nil nil))
 => 0
(call nft (create-token nil nil))
 => 1
(call nft (create-token nil nil))
 => 2

(asset/balance nft *address*)
 => #{1,2,0}

(asset/transfer nft [nft #{1 2}] nil)

(asset/balance nft *address*)
 => #{0}
```

Would expect the transfer (penultimate line) to fail?

**Comment by helins** [comment]
@Engelberg It seems to fail now because "Receiver does not have receive-asset function".

Is that good enough?

**Comment by Engelberg** [comment]
Yes, the problem wasn't really a problem of circularity, it was a problem of being able to send to actors that shouldn't have been able to receive. It's just that the bug was originally found testing against the asset actor itself. So this error message seems appropriate.
