### ISSUE TITLE
Extend `defined?` for querying other accounts

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#444]
2 improvements to consider about `defined?`:

- Add a 2-args arity that allows for checking if a symbol exists in another account.
- Make that a proper function, not a macro, akin to `lookup-meta`, so that the `name` can be provided dynamically.

This would be notably useful for interacting with contracts that **may** define extra behavior via additional (optional) callable functions. Then, this improved `defined?` would allow for easily checking if a given contract implements those optional behaviors.

**Comment by mikera** [comment]
Sounds plausible, just wondering what particular use case is motivating this? When would you expect on-chain code to make a decision based on what another actor supports? At first glance, this is an anti-pattern that should be discouraged.
