### ISSUE TITLE
Implement `Comparable` for all cells

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#446]
Not a top priority by some cells seem to be sortable (e.g. keywords) while others are not (e.g. symbols). Implementing `Comparable` for all cells is desirable since they are "just data". I realized this when sorting environment symbols failed.

**Comment by mikera** [comment]
Sounds sensible though there are important questions on semantics.

Should every cell be comparable with every other cell? Possibly not.... comparisons only really seem to make sense on sortable subtypes of cells.

I can see a case for comparisons within the following subtypes:
- Keywords
- Symbols
- Numeric values (but note the difference between numeric comparison and identity based comparison... e.g. is `0` equals to `0.0`?)
- Blobs (lexicographic sort)
- Characters (unicode code point order?)

Also an open question if such comparisons are available to CVM code, e.g. do we want a `compare` core function? And if so what does it do with incompatible types?

**Comment by mikera** [comment]
Recent commits add Comparable for all the above types

**Comment by mikera** [comment]
Closing as believe this is now complete
