### ISSUE TITLE
`AString.print()` should notify when the printer limit is exceeded 

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#461]
It seems all other cells `.print()` up to the authorized limit, after which `<<Printer limit exceeded>>` is appended.

`AString.print()` is a lot more casual and simply does a no-op if it detect that the string cannot be printed in full within the limit.  This leads to very confusing outputs, it took me a while to understand why large strings were seemingly "invisible" when inspecting them. A preferred behavior would be to print the portion that can be printed within the limit and append the warning above.

Is there a technical reason for keeping the status quo?

**Comment by mikera** [comment]
Let me double check the invariants expected but looks like behaviour should be the same.

**Comment by helins** [comment]
Improvement on `develop`, at least now it prints that the limit is exceeded (but without printing the portion of the string that could have been printed within the limit, so not yet on par with other types)

**Comment by helins** [comment]
Strings past the limit are still not partially printed, the output is only `<<Printer limit exceeded>>`

**Comment by helins** [comment]
False alert, I didn't notice the version has been updated and was still working against 0.7.10-SNAPSHOT.
