### ISSUE TITLE
Apparent issue where Peers stop merging Beliefs

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/convex#469]
Scenario:
- 10 Peers in separate Processes
- 100 Clients in separate client process sending transactions (back-to-back)

Problem:
- After some time / potentially randomly Peers stop merging Beliefs (stops in logs `New merged Belief update`)
- Some peers stop a few seconds earlier
- Peers continue to receive Beliefs (`Valid Belief received`)

@helins please add any more detail you can find

**Comment by helins** [comment]
To be more precise, this happens especially when:

- Everything runs locally
- Clients transact using a connection pool connected to >= 4 peers (5 becomes clearly noticeable)
- An RTT delay of 100ms is introduced on `localhost`, then it sometimes takes only a few seconds for things to halt
- Peers do not log any error

To confirm but using 16x bigger TCP/IP buffers didn't seem to make a noticeable difference.

**Comment by helins** [comment]
More intel:

- A 50ms delay looks equally as bad as 100ms (hard to tell if better or worse)
- Only 10 clients instead of a 100 (10x less load) looks equally as bad (hard to tell once again), will investigate more tomorrow

**Comment by helins** [comment]
10 peers, 5 connections shared with 100 accounts

**After getting stuck**

Received beliefs: ~100 / sec
Sent beliefs: ~ 10 - 20 / sec, **but peer 5 and 6 are stuck at 0** !

| Peer | Clients? | Consensus Point | Proposal Point | N blocks |
|---|---|---|---|---|
| 0 | Yes | 170 | 175 | 175 |
| 1 | Yes | 170 | 175 | 175 |
| 2 | Yes | 170 | 175 | 175 |
| 3 | Yes | 170 | 175 | 175 |
| 4 | Yes | 170 | 175 | 175 |
| 5 | No | 172 | 172 | 172 |
| 6 | No | 172 | 172 | 172 |
| 7 | No | 169 | 172 | 172 |
| 8 | No | 169 | 172 | 172 |
| 9 | No | 170 | 175 | 175 |

**Comment by helins** [comment]
Peers 5 to 8 look funky and if they are faulty, they wouldn't be enough stake to converge.
5 and 6 are especially suspicious.

**Comment by helins** [comment]
Each peer is connected to every other peer

**Comment by mikera** [comment]
This is super useful, thanks. I suspect the problem is overloading in queues when Peers are sending too many beliefs to each other, so it needs some throttling. Not super trivial but working on a fix soon!

**Comment by mikera** [comment]
This has been resolved in recent networking fixes. Closing as complete, if a different problem arises please open a new issue @helins.
