### ISSUE TITLE
Stabilise the Convex Public License

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#474]
As discussed today, here are some outstanding issues to ensure the project is properly open-sourced.
This is a priority item as it impedes the development of the ecosystem.

A) ~Ensure any copyright statement applied to any work in the repo clearly identifies the relevant license~

B) ~Clarify which license is applied to which "module" (e.g. CPL for core modules, Apache 2.0 for the rest). Probably in the core README alongside the copyright statement.~

C) Provide the "Convex Network Governance Rules" mentioned in the CPL, otherwise it cannot be completed.

C) Finalize a first version for CPL since being marked as draft / wip causes uncertainty.

D) ~Disambiguate "linking" since it has a direct impact on what is considered a "Derivative Work". E.g. During our discussion, in spite of packaging the Work in a single object, the Shell was deemed to merely link to the Work and hence is **NOT** considered a Derivative Work. Working assumption seems to be that a Derivative Work implies modifying the Work, as opposed to merely building on top of it in any way.~

E) ~Add a clear definition of forking (e.g. public permissionless network) since one of the main goals of this custom license is to protect against it.~

F) Relating to E, clarify usage pertaining to all those different kinds of permissioned networks (networks which restrict participation in any way).

**Comment by mikera** [comment]
Happy to take PRs on any of the above.

Network Governance Rules are incorporated by reference, won't be in the license itself and they may evolve over time. Also probably won't be finalised in a stable version until main network launch (since that is when we need them for). But happy to make a quick draft of the key bullets

**Comment by helins** [comment]
Remember it's perfectly fine for a license to evolve (and referenced addendums completing it). On the other hand, being marked as a draft creates a lot of legal uncertainty.

**Comment by mikera** [comment]
I will review and remove the "draft" parts today if that helps, we will consider it a real but "alpha" version I guess.

**Comment by mikera** [comment]
All of these points are addressed in recent changes to CPL and introduction of CNGRs. @helins please provide either provide specific additional feedback or close this issue as complete.

**Comment by helins** [comment]
Thanks for the prompt progress 👍 

Relative to the goal of ensuring Convex is effectively open-source:

G) Please make the CNGR easier to find (e.g. providing a link in the CPL)
H) Stabilise a first version of the CNGR since they are an explicit requirement of the CPL (cf. earlier comment about marking documents of legal importance as drafts)
I) Clause 6 (Trademarks) mentions a NOTICE file, what/where is it?

I believe the above should be enough to close this particular issue. In my opinion, the current CNGR are good enough relative to the mainnet (and protecting any contribution done towards it). 

The only aspect I see in the CNGR that will require further thought is the Subnets clause. We'll have to discuss it because the conditions might be too narrow for any practical use. It also relates to the definition of "Economic Asset". It is so broad that I cannot picture a single thing in this world that would not qualify as an "Economic Asset".

That being said, let me stress the fact this is not a blocker for completing this issue. This is something we can address afterwards and engage more actively with the community.

**Comment by mikera** [comment]
OK closing this for now as immediate issues fixed.

I'm not too concerned about Subnet clause, since it allows plenty of flexibility in the future (if someone has a different proposed way of running a Subnet, it can be easily agreed as long as it is not against the interests of the ecosystem).
