### ISSUE TITLE
Public API for advancing the CVM timestamp

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#484]
I've been using a hacky way for advancing the CVM timestamp (and executing scheduled transactions) that broke recently. Important for testing scheduling deterministically.

Note: not a priority for cloud testing per se but avoids breaking the current tooling (i.e. Shell)

**Comment by mikera** [comment]
A couple of potentially useful functions have been made public in `State` so you should be able to do this.

Note however this is internal stuff and not likely to be part of any official public API, so caveat emptor as usual.....

**Comment by mikera** [comment]
Please confirm if the above solves your problem and close if so, thanks @helins

**Comment by helins** [comment]
Does the job, thanks.
I would keep it more official since it is the only way of reliably testing scheduling (which is a key feature of Convex).
