### ISSUE TITLE
`Missing data in Order` extremely pervasive

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#488]
During a 10 min simulation, a single peer can log it hundreds of thousands of times, commonly looking after the same hash several times. This is bound to have a very negative impact on performance.

**Comment by helins** [comment]
E.g. Counts from peer log files based on latest `develop`:

```
2.cvx:2
3.cvx:160
4.cvx:87
7.cvx:2
5.cvx:85
1.cvx:110759
0.cvx:2
8.cvx:34736
9.cvx:424428
6.cvx:495000
```

**Comment by mikera** [comment]
At some point we will just turn of the logging. A Peer must be robust to this error (an attacker could deliberately forge an order with missing data, for example). The real problem to solve is why it is so frequent under normal-ish conditions.

**Comment by mikera** [comment]
Will continue investigating this one.  The network should be robust to these, but happening this frequently is a concern (and potential significant performance loss)

**Comment by mikera** [comment]
Closing because it's an old issue that I think has been solved long ago
