### ISSUE TITLE
`Incoming belief queue full` is pervasive

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#489]
After #488 , this seem to be the most logged error. It usually starts right from the beginning until the end and I don't think it was such an obvious issue with Convex `0.7.11`.

**Comment by mikera** [comment]
Is the Peer suffering from this still active / operational?

**Comment by mikera** [comment]
I found one reason that might have caused this, fix above. It's not critical but might slow things down in some cases.

**Comment by helins** [comment]
Recent changes seem to help but the issue is still present.

E.g. Counts from peer log files (10 min run):

```
0.cvx:25
2.cvx:42
9.cvx:107
1.cvx:1122
6.cvx:5415
7.cvx:1630
3.cvx:2824
5.cvx:1322
4.cvx:10588
8.cvx:289
```

**Comment by helins** [comment]
Overall, looks improved as of `80589055`.

There are some spikes in numbers (e.g. 20k occurences in a single peer) but more typical numbers per run now look closer to this:

```
log/peer/1.cvx:100
log/peer/5.cvx:25
log/peer/8.cvx:17
log/peer/9.cvx:7
log/peer/4.cvx:934
log/peer/3.cvx:1997
```

**Comment by mikera** [comment]
OK this looks much more reasonable / expected. Network should be robust to these.

Closing as expected behaviour.
