### ISSUE TITLE
Check Antlr version

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#494]
On latest `develop`, I get the following warning:

```
ANTLR Tool version 4.13.0 used for code generation does not match the current runtime version 4.12.0
ANTLR Runtime version 4.13.0 used for parser compilation does not match the current runtime version 4.12.0
ANTLR Tool version 4.13.0 used for code generation does not match the current runtime version 4.12.0
ANTLR Runtime version 4.13.0 used for parser compilation does not match the current runtime version 4.12.0
```

**Comment by mikera** [comment]
When are you getting that warning?

**Comment by helins** [comment]
The first time the Reader is used during a load test. However, I can't replicate it by just not running a simulation and reading something at the REPL.

Mysterious but probably linked to how logging is setup, albeit not exactly sure.  Warning vanishes after moving the namespace setting that up higher in `:require` 🤔 

Not crucial but probably recent. Don't sweat it unless you updated ANTLR or something like that.

**Comment by mikera** [comment]
Doesn't seem to be happening in any of the tests I am running. Have updated ANTLR to `4.13.1` in any case, perhaps this has helped.
