### ISSUE TITLE
Missing data in Etch during block analysis

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#495]
A `MissingDataExcception` is thrown when counting blocks and transactions from the peer's ordering after a cloud simulation, which prevents computing metrics like TPS, block size, etc. This doesn't seem to occur for tiny simulations (e.g. 10 users over 2 minutes) but becomes systematic for anything more involving. I have never encountered that with Convex `0.7.11`.

In principle, peers are shutdown cleanly from within the process. I even flush Etch just in case afterwards. Only then are processes actually killed.

Might be related to #487 and/or #488.

**Comment by helins** [comment]
Seems to be resolve (tested against `80589055`).
No issue across 7 runs, whereas it was systematic previously.

**Comment by mikera** [comment]
OK closing as it looks like we have caught this particular issue.
