### ISSUE TITLE
PeerGUI not Mac compatible

### ISSUE THREAD

**Issue by pferdy** [Convex-Dev/convex#501]
Copy and Paste into PeerGui does not work, either with keyboard or right click.

**Comment by mikera** [comment]
What keys do you expect to work for Copy and Paste? You may need to help me debug this one as I don't have a Mac :-)

**Comment by pferdy** [comment]
To use a keyboard shortcut, press and hold one or more modifier keys and then press the last key of the shortcut. For example, to use Command-C (copy), press and hold the Command key, then the C key and then release both keys. 

Mac menus and keyboards often use [symbols for certain keys](https://support.apple.com/en-gb/guide/mac-help/what-are-those-symbols-shown-in-menus-cpmh0011/mac), including modifier keys:

- Command (or Cmd) ⌘. 
- Shift ⇧
- Option (or Alt) ⌥
- Control (or Ctrl) ⌃
- Caps Lock ⇪

On keyboards made for Windows PCs, use the Alt key instead of Option, and the Ctrl key or Windows logo key instead of Command.

I am happy to test both Apple and Windows keyboards.

**Comment by mikera** [comment]
I added a simple Cut / Copy / Paste right click menu. I think it should work on Mac now, though might need your help to test a new jar!

**Comment by pferdy** [comment]
Where is the new Jar?

**Comment by mikera** [comment]
Downloadable link to latest snapshot here:

https://drive.google.com/file/d/1T16XNA_rxlmWNv5_DtMr7-5Y5pVT3zao/view?usp=sharing

**Comment by pferdy** [comment]
PeerGui runs - but I can't see where to type in any code to create a fungible token.  
I can type into the Message menu, but I can't paste with RH click (there is no edit menu)

**Comment by pferdy** [comment]
Undo and redo would also be useful.

**Comment by mikera** [comment]
OK I think this specific issue is solved as PeerGUI is running and copy / paste work. If there is a new feature request please open a new issue!

**Comment by ash-mcc** [comment]
As a late to this Mac user, I'm just adding a note to warn that when in Convex's Desktop GUI, copy&paste are bound to the ctrl+c & +v keys rather to the Mac's normal cmd+c & +v keys. That might be a default Java thing rather than a Convex thing.
