### ISSUE TITLE
Tutorial or quck-start needed

### ISSUE THREAD

**Issue by WorldsEndless** [Convex-Dev/convex#505]
I have been avoiding the blockchain as much as possible for years; I know nothing of its terminology or concepts. But if I am to get involved with it, Convex seems the most promising and friendly way for a lisp & clojure man like myself. But I have not seen an on-rampt to Convex, either. Is there a typical block-chain equivalent to "hello world" or "todolist app"? Am I missing documentation somewhere? In short, I would love my block-chain starting point to be convex, but I have no idea where to begin or what can actually be done with it.

**Comment by mikera** [comment]
Thanks for the good question!

The easiest way with Convex is probably just to try the sandbox at https://convex.world/sandbox

This is an interactive shell / REPL which lets you do basically anything that a user can possibly want to do on the Convex test network. Create smart contracts, mint digital assets, write general purpose CVM code etc. Each user effectively gets their own personally Lisp machine.

For a bit more sophisticated use you can run a local Convex test network using either the Convex GUI or Convex CLI from this repository. 

As for tutorial material there is some useful stuff here: 
- https://convex.world/cvm
- https://github.com/Convex-Dev/convex/tree/develop/convex-core/src/test/resources/examples

Often the best thing though is to just ask on the Discord! Myself and others are always happy to help, and discussing design issues often helps us come up with better solutions so it helps the project a lot as well :-)
- https://discord.com/invite/xfYGq4CT7v

**Comment by mikera** [comment]
CAD026 has since been created, which provides a broad description and introduction to Convex Lisp

https://github.com/Convex-Dev/design/tree/main/cad/026_lisp
