### ISSUE TITLE
The Desktop locks up when trying to display an emoji value.

### ISSUE THREAD

**Issue by ash-mcc** [Convex-Dev/convex#512]
The Desktop locks up when trying to display an emoji value...

When I put an emoji value, e.g. 🖼️, into the environment of an account `#99` then ask the Desktop's REPL to eval `(account #99)`, it lock ups trying to display the emoji in the output panel of the REPL.

Having an emoji value in an account's environment has no detrimental affect on the core Convex system - just the Desktop's display functionality as far as I can see.

Cheers, Ash

**Comment by ash-mcc** [comment]
...simpler reproduction of the problem by simply entering "🖼️" into the Desktop's REPL.

If the Desktop's display lib/tech doesn't easily support the display of emojis then perhaps they can be scanned for and simply substituted for a placeholder character.

**Comment by mikera** [comment]
![image](https://github.com/user-attachments/assets/0de279be-4a2b-47d0-990f-b6fa4190cb19)

Emojis seem to work for me on the latest desktop? What platform are you running on?

**Comment by ash-mcc** [comment]
Hi Mike, I'm running Convex on macOS (Sonoma).
But I've pulled and built the latest `develop` branch and I can no longer reproduce the problem.
(I've updated to your latest commits several times over the last week and didn't keep a note of the commit ID that manifested the problem. It was reproducible at the time though. Anyway, no longer a problem so I'l close this. Thanks.)

**Comment by mikera** [comment]
OK sounds good. I don't think anything has changed that would specifically affect emoji rendering bit glad it works now!
