### ISSUE TITLE
There's no way back from initialising a market's cvx-pool to 0

### ISSUE THREAD

**Issue by ash-mcc** [Convex-Dev/convex#517]
### There's no way back from initialising a market's cvx-pool to 0

1. Create a fungible `AshCoin`
2. Create a Torus market for it.
3. Initialise that market's `cvx-pool` to `0`: `(torus/add-liquidity AshCoin 1 0)`
4. The price is then `0.0` and there's no way to change that.

(Mike - this happened in today's workshop for protonet.)

Cheers, Ash

**Comment by mikera** [comment]
Great spot, thanks Ash! Will fix ASAP

**Comment by mikera** [comment]
Fixed in latest `develop`. If either of the balances is zero, there is `nil` price and zero liquidity.
