### ISSUE TITLE
Unexpected Error: `blob` with odd-length hexstring

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#54]
Calling `blob` with a hexstring of odd length results in a fatal error and breaks the executing account.

![Screenshot from 2021-04-21 19-38-54](https://user-images.githubusercontent.com/17478152/115597161-42f6b700-a2d9-11eb-9647-5d1be001fb85.png)

**Comment by mikera** [comment]
I believe this has been resolved in recent releases. We are sticking with `:CAST` for now because it is a failed cast, and this is probably the most useful error.
