### ISSUE TITLE
Booleans should not be considered as numbers

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#73]
In a low-level language like C, booleans are simply integers and can behave as such. However, in a high-level language, this should be unexpected for the sake of type safety. Even Java agrees.

So I strongly argue that the following should be illegal:

```clojure
(number? true)  ;; => true

(inc true)  ;; => 2
```

Looking at the implementation of `CVMBool.longValue`, it looks like it has been designed on purpose. Any rationale?

**Comment by helins** [comment]
Current behavior is fine now (booleans are not numbers, explicit cast needed). Shall we close?

**Comment by mikera** [comment]
Yes good I think!
