### ISSUE TITLE
Consider if Blobs should cast to Long

### ISSUE THREAD

**Issue by kroezone** [Convex-Dev/convex#9]
What should happen with:

```clojure
(long 0xFF) ;; 255?
(long 0x1000) ;; 4096>
(long 0xFFFFFFFFFFFFFFFF) ;; -1?
(long 0xFFFFFFFFFFFFFFFFFF) ;; argument error?
```

Behaviour is currently undefined, seems to be an issue.

**Comment by helins** [comment]
Looks fixed.

**Comment by mikera** [comment]
Have implemented this. I have a couple of use cases where it is important (e.g. using timestamps as blob-map keys)
